name: Stremio Telegram
version: "1.5.0"
slug: stremio_telegram
description: A self-hosted addon that connects to your Telegram user account, discovers joined private broadcast channels, and indexes uploaded videos for browsing, searching, and streaming through your server

url: https://github.com/HaCStream/stremio-addon
image: ghcr.io/hacstream/stremio-addon
webui: "http://[HOST]:[PORT:8001]/"
ingress: true
ingress_port: 8001
ingress_entry: /
arch:
  - amd64
startup: application
boot: auto
init: false
ports:
  8000/tcp: 8000
  8001/tcp: 8001
timeout: 30
options:
  ADDON_URL: ""
  API_KEY: ""
  API_ID: 0
  API_HASH: ""
  USER_SESSION_STRING: ""
  CACHE_MB: 512
  CHANNEL_IDS: ""
  ai:
    AI_SEARCH_ENABLED: false
    GEMINI_API_KEY: ""
    REQUIRE_AI_SUFFIX_FOR_AI_SEARCH: true
  debug:
    DEBUG_ENABLED: false
    DEBUG_HOST: "0.0.0.0"
    SKIP_DEBUG_AUTH: false
schema:
  ADDON_URL: url
  API_KEY: password
  API_ID: int(1,)
  API_HASH: password
  USER_SESSION_STRING: password
  CACHE_MB: int(0,)
  CHANNEL_IDS: str?
  ai:
    AI_SEARCH_ENABLED: bool
    GEMINI_API_KEY: password?
    REQUIRE_AI_SUFFIX_FOR_AI_SEARCH: bool
  debug:
    DEBUG_ENABLED: bool
    DEBUG_HOST: str
    SKIP_DEBUG_AUTH: bool
